## This will be generated by a python script

# Update the task status of the player that completed the task
# If multiple people complete the task at the same time, select one at random
scoreboard players set @r[scores={CompleteTask=1}] TaskStatus 4

# When a player completes a task, let everyone know
execute if score @p[scores={TaskStatus=4}] TaskStatus matches 4 run tellraw @a [{"selector": "@p[scores={TaskStatus=4}]"},{"text": " has completed the task!"}]

# On call, give the player the prompt to select a player to lose time
tellraw @p[scores={TaskStatus=4}] {"text": "Choose a player to lose time:\n"}

# Generate the list of players from the provided list of players. Player will only appear in prompt if they are still alive.
# On click, call the trigger associated with each username
execute if score bballty115 ActivePlayer matches 1 run tellraw @p[scores={TaskStatus=4}] {"text": "bballty115\n", "click_event": {"action": "run_command", "command": "/trigger bballty115"}, "color": "aqua"}

# Give user the undo prompt in the event of a misclick
tellraw @p[scores={TaskStatus=4}] [{"text": "[Clicked this prompt by mistake? Click ", "italic": true}, {"text": "here", "underlined": true, "color": "yellow", "click_event": {"action": "run_command", "command": "/trigger UndoCompleteTask"}}, {"text":" to undo!]", "color": "white", "underlined": false}]

# Once a player has all the resources needed to move forward, set their task completion flag to 5
scoreboard players set @p[scores={TaskStatus=4}] TaskStatus 5


# Once a player with a task status of 5 selects a player to lose time, remove time from that
#  player, announce that that player lost time and update the task completer's status
execute if score @p[scores={TaskStatus=5}] bballty115 matches 1 run tellraw @a [{"text": "bballty115 has lost time.", "color": "blue"}]
execute if score @p[scores={TaskStatus=5}] bballty115 matches 1 run scoreboard players set @p[scores={TaskStatus=5}] TaskStatus 6
execute if score @p[scores={TaskStatus=6}] bballty115 matches 1 run scoreboard players remove bballty115 TimeHours 2

# Grant the player who completed the task an hour back
scoreboard players add @p[scores={TaskStatus=6}] TimeHours 1

# Reset the task selected, task announced, and task status of all players
# Also reset reroll votes if no task has been rerolled yet
execute if score @p[scores={TaskStatus=6}] TaskStatus matches 6 run scoreboard players set #task_selected Counter 0
execute if score @p[scores={TaskStatus=6}] TaskStatus matches 6 run scoreboard players set #task_announced Counter 0
execute if score @p[scores={TaskStatus=6}] TaskStatus matches 6 run execute unless score #task_rerolled Counter matches 1 run scoreboard players set @a PromptedReroll 0
execute if score @p[scores={TaskStatus=6}] TaskStatus matches 6 run execute unless score #task_rerolled Counter matches 1 run scoreboard players set #reroll_votes Counter 0
execute if score @p[scores={TaskStatus=6}] TaskStatus matches 6 run scoreboard players set @a TaskStatus 0
